spring.application.name=rsv-stomp-stack
# H2 DB 설정 (메모리 방식)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 서버 실행 시마다 테이블 재생성 (개발 단계 CoC)
spring.jpa.hibernate.ddl-auto=update
# H2 콘솔 활성화 (브라우저에서 DB 확인 가능)
spring.h2.console.enabled=true